### ISSUE TITLE
error about reproduction

### ISSUE THREAD

**Issue by Zora-zjj** [AnnikaLindh/Controllable_Region_Pointer_Advancement#1]
Very appreciate it for this paper!!
I run your github and meet some error：

python model/main.py --mode=train

Traceback (most recent call last):
  File "model/main.py", line 441, in <module>
    launch_training()
  File "model/main.py", line 260, in launch_training
    _CONFIG['num_epochs'], loss_writer)
  File "model/main.py", line 65, in train
    example_ids=dataloader_train_inference.dataset.example_ids)
  File "F:\ZJJ\13_Controllable_Region_Pointer_Advancement\evaluate\text_metrics.py", line 55, in setup
    self.gts_all[example_id] = gts_all_base[example_id.split('_')[0]]
KeyError: '10002456'

Thank U.

**Comment by AnnikaLindh** [comment]
Hi Zora,

Thanks for your interest in our code. :)
I'm not getting the same error on my end when I re-download the code and run it. Could you copy and paste what the output is before the error? It should say "To replicate, run with the following parameters:" followed by a list of parameters. And eventually it should say EPOCH 1 if it started training, but your error seems to occur before that.

/ Annika

**Comment by AnnikaLindh** [comment]
I'm closing this, but please re-open if you need more help with this.
